apiVersion: v1
kind: Secret
metadata:
  name: banking-secret
  namespace: banking
type: Opaque
stringData:
  db-username: root
  db-password: changeme
  jwt-secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7e34f79b6c0c3e7d3c0b4b7f2
